github: carrilloapps
patreon: carrilloapps
ko_fi: carrilloapps
buy_me_a_coffee: carrilloapps
custom:
  - name: "Website"
    url: "https://carrillo.app"
  - name: "Blog"
    url: "https://carrillo.app/blog"
  - name: "Telegram"
    url: "https://t.me/carrilloapps"